#!/bin/bash
GIT_DIR=$(pwd)

# The basics
ln -s ${GIT_DIR}/bash_aliases ~/.bash_aliases
ln -s ${GIT_DIR}/bashrc ~/.bashrc
ln -s ${GIT_DIR}/profile ~/.profile
ln -s ${GIT_DIR}/dircolors ~/.dircolors
source ~/.bashrc

# Vim
if [[ -e '/usr/bin/vim' ]]; then
    ln -s ${GIT_DIR}/vimrc ~/.vimrc
else
    echo "Vim not found. Fix that shit."
    exit 1
fi

# Guake
if [[ -e /usr/local/bin/guake ]]; then
    ln -s ${GIT_DIR}/guake ~/.gconf/schemas/apps/guake
    guake -q
    ( nohup guake & ) &> /dev/null
    exit 0
else
    echo "Guake not found. Dafuq you doin' without Guake, bro?"
    exit 1
fi
