#!/bin/bash

# Add J-Link to path.
export PATH=/opt/SEGGER/JLink:${PATH}

export GOPATH=${HOME}/go_workspace
export GOBIN=${GOPATH}/bin
export PATH=/opt:${PATH}:${GOBIN}:~/scripts

#apt-cache policy golang | grep -i "installed" | grep -i "none" &> /dev/null

if [ $? -eq 0 ]; then
    export GOROOT=/opt/go
    export PATH=${PATH}:${GOROOT}/bin
fi

if [ -d ${HOME}/scripts ]; then
    export PATH=${PATH}:${HOME}/scripts
fi

export CATALINA_HOME=/opt/apache-tomcat-7.0.68
alias tomup=${CATALINA_HOME}/bin/startup.sh
alias tomdown=${CATALINA_HOME}/bin/shutdown.sh
alias tomwatch="tail -f ${CATALINA_HOME}/logs/catalina.out"

if [ -d /opt/gradle-2.12 ]; then
    export PATH=${PATH}:/opt/gradle-2.12/bin
fi

alias tks="tmux kill-session -t 0"
function tmux_init()
{
    cd ${HOME}

    # Source Window
    tmux rename-window "Source"
    tmux split-window -p 10
    tmux split-window -h -t 1
    tmux select-pane -U

    ## Search Window
    #tmux new-window -n "Search"

    ## Build/Program Window
    tmux new-window -n "Build/Program"
    tmux split-window -h -t 1.0

    # Debug/Run Window
    tmux new-window -n "Debug/Run"
    tmux split-window -t 2.0 -h
    tmux split-window -t 2.1

    ## Misc Window
    tmux new-window -n "Misc"
    tmux split-window -t 3.0 -h
    tmux split-window -t 3.1 -h
    tmux split-window -t 3.0

    ## Go back home
    tmux select-window -t 0
    tmux select-pane -t 0
}
