#!/bin/bash

export GOPATH=${HOME}/go_workspace
export GOBIN=${GOPATH}/bin
export PATH=${PATH}:${GOBIN}

apt-cache policy golang | grep -i "installed" | grep -i "none" &> /dev/null

if [ $? -eq 0 ]; then
    export GOROOT=/opt/go
fi
